---
- name: Gather facts
  openshift_facts:
    role: common

- block:
  - name: Clear yum cache
    command: "yum clean all"
    ignore_errors: true

  - name: Install the required rpms
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - NetworkManager
    - origin-excluder
    - origin-docker-excluder
    when: openshift.common.deployment_type == 'origin'

  - name: Install the required rpms
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - NetworkManager
    - atomic-openshift-excluder
    - atomic-openshift-docker-excluder
    when: not openshift.common.deployment_type == 'origin'

  - name: Start NetworkManager and network
    service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    with_items:
    - NetworkManager
    - network
  when: not openshift.common.is_atomic | bool
